### ISSUE TITLE
[Bug]: Magic Plugin damage miscalculation

### ISSUE THREAD

**Issue by neYaANK** [magemonkeystudio/divinity#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spell deals 9 damage

### Expected Behavior

Spell deals 5 damage

### Steps To Reproduce

1. Use Damage in Magic
2. Set damage value to be 5
3. Use the spell

### Environment

```markdown
- Server Software: Spigot 1.18.2
- ProRPGItems Version: Tested on both 1.0.6-R0.7 and 1.0.7-R0.2-SNAPSHOT (dev)
- ProMCCore Version: 1.1.0-R0.4
- Plugins:
ProtocolLib:5.0.0,
ProSkillAPI:1.1.13,
ProSkillAPIParties:1.1.0.2,
Magic:10.8.11
```

**Comment by neYaANK** [comment]
From what I see, the issue may be here
https://github.com/promcteam/prorpgitems/blob/927b17fe0331afa3f78136468dc754b8956fcb60/src/main/java/su/nightexpress/quantumrpg/manager/listener/object/VanillaWrapperListener.java#L294C1-L295C1
As after using a spell, wand is not considered as a weapon and damage decreases by 1. Still, not sure how to handle it

**Comment by Travja** [comment]
This is damage done via the Magic plugin? Through casting a spell with a stick as a wand?

**Comment by neYaANK** [comment]
Yep, that's right. Divinity is not used, but installed and affects the damge dealt by Magic. And the wand is stick, yeah.

**Comment by Travja** [comment]
I assume that some updates along the way resolved this. I installed Magic and am not seeing the described behavior.
