### ISSUE TITLE
[Bug]: There is an error in the Gems module's calculation method for increasing maximum health.

### ISSUE THREAD

**Issue by Ghost067** [magemonkeystudio/divinity#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set a gemstone to increase its maximum health by 10 points, embedding it on any armor that has no maximum health attribute and only wears this armor will increase my health by 20 points.

### Expected Behavior

When I set a gemstone to increase its maximum health by 10 points, embedding it on any armor that has no maximum health attribute and only wears this armor will increase my health by 10 points.

### Environment

```markdown
- Server Software: PaperSpigot 1.16.5
- Divinity Version: Latest version
- Codex Version: Latest version
- Plugins: Codex、Divinity
```

**Comment by Travja** [comment]
You say "latest version" but I really need to know the whole version numbers of the plugins.

**Comment by Ghost067** [comment]
Sorry,Codex is 1.0.0-R0.17-SNAPSHOT、Divinity is 1.0.0-R0.17-SNAPSHOT.

**Comment by Ghost067** [comment]
@Travja Hey, have you dealt with the issue I gave feedback on?
