### ISSUE TITLE
[Bug]: Range Stat

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/divinity#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The item generator has a RANGE stat that does not appear on the item. Also it is not in /divinity set stat

### Expected Behavior

As I understand it, this is a removed stat. It shouldn't be on the list

### Steps To Reproduce

1. Create and open some item generator
2. Set the stat chance RANGE to 100%, the rest to 0
3. Set the minimum number of stats to 1
4. Get an item from the generator

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Divinity Version: 1.0.0-R0.17-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (3): PlaceholderAPI, ProtocolLib, spark
```

**Comment by goflishMC** [comment]
The code for the range stat was removed by the original dev. We will be moving it from the item generator soon. We've looked into adding it back, but there's no good way to do it without causing major issues. Minecraft just doesn't have good options for that type of stat.
