### ISSUE TITLE
[Bug]: Hand Stat for non-weapon

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/divinity#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The item generator cannot set the Hand stat for non-weapons, such as a stick. But I can add this stat by using the command

### Expected Behavior

Adding stats to all generator items

### Steps To Reproduce

- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Divinity Version: 1.0.0-R0.17-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (3): PlaceholderAPI, ProtocolLib, spark

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Divinity Version: 1.0.0-R0.17-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (1): PlaceholderAPI, ProtocolLib, spark
```

**Comment by Travja** [comment]
@3Lord3 I think this actually works now? Though I'm not sure exactly how your set up was before to know what is or isn't getting added. If you're still around, could you test this again with newer dev builds and let me know if this is still an issue?
