### ISSUE TITLE
[Bug]: Offhand shield

### ISSUE THREAD

**Issue by 3Lord3** [magemonkeystudio/divinity#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The shield has logic rewritten by the plugin, but it does not work in the offhand (as indicated in the config)

### Expected Behavior

The shield works the same in both hands, even if it doesn't work for stats

### Steps To Reproduce

1. Get shield
2. Try to block damage in offhand

### Environment

```markdown
- Server Software: Purpur 1.20.6-2227-79d199c (MC: 1.20.6)*
- Divinity Version: 1.0.0-R0.17-SNAPSHOT
- Codex Version: 1.0.0-R0.17-SNAPSHOT
- Plugins: Paper Plugins: (3): Codex, Divinity, Fabled | Bukkit Plugins: (1): PlaceholderAPI, ProtocolLib, spark
```

**Comment by Travja** [comment]
I know I've done some work on shields fairly recently and had them working. So I'm going to close this as I do believe things are working properly.
