### ISSUE TITLE
[Enhancement] Add new feature to item import

### ISSUE THREAD

**Issue by HuyYon** [magemonkeystudio/divinity#242]
Has the following features:
create an item according to stats damage defense... lore.... (Divinity's command)
add command /qrpg save (name)
Used to save hand-held items created in the game (not item generators) into a file
When needed, use /qrpg give (name) to get that item from the file for the player

**Comment by goflishMC** [comment]
> Has the following features: create an item according to stats damage defense... lore.... (Divinity's command) add command /qrpg save (name) Used to save hand-held items created in the game (not item generators) into a file When needed, use /qrpg give (name) to get that item from the file for the player

You can already create/save items from in game. `/itemgen create` and `/itemgen edit`

This was added 2 years ago
