### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by v8v8** [magemonkeystudio/divinity#254]
How to Set Divinity Attribute for Items in MythicMobs

**Comment by Travja** [comment]
You should be able to use `/mm import`? to import the item for use with mythic mobs

**Comment by v8v8** [comment]
> 你应该能够使用？导入物品以用于神话生物`/mm import`

Please optimize the ability to write divinity attributes directly in the mythicmobs configuration file instead of using /mm import, which is not free at all! Unable to change divinity items imported into mythicmobs

**Comment by Travja** [comment]
Divinity items use NBT data to set attributes and things. Unless MM has a way to do that easily, the import command is the only option.

**Comment by v8v8** [comment]
Please add lore recognition for divinity recognition, I can add lore (magical: 100) to mythicmobs to add attributes to items!

**Comment by v8v8** [comment]
Expect the following functionality to recognize the divinity attribute  ↓↓↓↓
（mythicmobs items profile）
SkeletonKingSword:
  Id: DIAMOND_SWORD
  Display: '&3Greatsword of the Skeleton King'
  Lore:
  - '&6Physical Damage:300~500'
  - '&6Magical Damage:100~200'
  - '&6Fire Damage:100~200'
  - '&6Poison Damage:100~200'
  - '&6Water Damage:100~200'
  - '&6Wind Damage:100~200'
  - '----------and------------'
  - '&6Physical Defense:100~200'
  - '&6Magical Defense:100~200'
  - '&6Fire Defense:100~200'
  - '----------and------------'
  - '&6PvP Damage:30'
  - '&6PvE Damage:50'

**Comment by v8v8** [comment]
> 神性物品使用NBT数据来设置属性和事物。除非 MM 有办法轻松做到这一点，否则导入命令是唯一的选择。

These are my proposed upgrades

**Comment by Travja** [comment]
I apologize, and I'm going to be a little blunt here. It's not worth my time to add in functionality to read stats from the lore just to better help create items in MM. Divinity is an item builder in itself and MM has capabilities to import other items. I'd rather not create a new solution to a problem that already has a solution.
