### ISSUE TITLE
Attribute Statistics Table

### ISSUE THREAD

**Issue by v8v8** [magemonkeystudio/divinity#255]
Please add a statistic table of players' Divinity attributes to make it easier for players to check their attributes.

**Comment by Travja** [comment]
What exactly are you asking for? We supply various placeholders that you can use to build your own implementation.

**Comment by TheKot1k** [comment]
> What exactly are you asking for? We supply various placeholders that you can use to build your own implementation.
I think he's asking for something like an indicator of current attributes, not attribute bonuses. Something like the result of adding up both types of attributes (vanilla and divinity)
