### ISSUE TITLE
[Bug]: There is a problem with durability

### ISSUE THREAD

**Issue by Ghost067** [magemonkeystudio/divinity#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the durability of the item is 0, the configuration file is set to "do not destroy the item if there is no durability", but the item's properties are still in effect.

### Expected Behavior

If the item's durability is 0, but the item's properties are invalid.

### Environment

```markdown
- Server Software: PaperSpigot1.16.5
- Divinity Version: 1.0.0-R0.30
- Codex Version: 1.0.0-R0.29
- Plugins: Only these two plugins.
```

### latest.log

The console does not output any errors.

**Comment by Travja** [comment]
Are you saying that the vanilla durability takes effect when the stat is set to 0?

**Comment by Ghost067** [comment]
No, I mean that when the durability of a weapon or armor set by the plugin is used to 0, and when the durability of the plugin named ProRPGItems is used, the durability will be displayed as 0 and the set properties are useless; However, the stats are still active when the durability is 0.

**Comment by Travja** [comment]
When the new build comes out, could you verify that this is still happening?

**Comment by Ghost067** [comment]
Okay, I'll give it a try now.

**Comment by Ghost067** [comment]
I'm sorry, but after my attempts, this issue still hasn't been fixed.

**Comment by Travja** [comment]
No worries, it was a bit of a long shot. But rules out the other issues being the cause. Which properties are the ones you're seeing still in effect?

**Comment by Ghost067** [comment]
I have tried all the attribute tags based on feedback from players on my server.

And there is another issue, the attribute about dodge rate in the Gems module is not working properly. Can you take a look at this problem? Thank you very much for this.

**Comment by Travja** [comment]
I need to know exactly what is being applied when it shouldn't be in order to figure out that's going on

**Comment by Ghost067** [comment]
I'm very sorry, I don't quite understand what you mean. My English level is not very good. If you need me to provide some test data, I will provide it to you tomorrow. I'm going to sleep now.

**Comment by Travja** [comment]
Yes, I need test data, or to know which attributes/stats are the problematic ones

**Comment by Ghost067** [comment]
As of now, all types of damage set in the damage.yml will still be useful after the durability is 0, as I just tested.
