### ISSUE TITLE
[Bug]: The stats for PVP damage and PVE damage cannot produce an effect when the percentage is negative.

### ISSUE THREAD

**Issue by Ghost067** [magemonkeystudio/divinity#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The question is as shown in the title.

### Expected Behavior

It works fine,

### Environment

```markdown
- Server Software: PaperSpigot1.16.5
- Divinity Version: 1.0.0-R0.30
- Codex Version: 1.0.0-R0.29
- Plugins: Only these two plugins.
```

**Comment by Travja** [comment]
Not sure what you're expecting it to do if the value is negative?

**Comment by Ghost067** [comment]
I want to make some weapons or armor that are specifically designed for PVP or PVE.

**Comment by Travja** [comment]
I don't think that pvp and pve damages really come into effect anywhere specifically. Other damage types should actually be used most of the time
